### ISSUE TITLE
Spawning agents from another agent

### ISSUE THREAD

**Issue by bangxiangyong** [bangxiangyong/connect-agentMET4FOF-smartupunit#4]
As we encountered an error in running the code at https://github.com/bangxiangyong/connect-agentMET4FOF-smartupunit/blob/master/DataReceiverAgent.py

The exception raised (simplified) was: 
```
 gen_agent = agentNetwork.add_agent(agentType= Met4FOFSSUDataReceiverAgent, log_mode=False)

EXCEPTION <class 'TypeError'>: Pickling an AuthenticationString object is disallowed for security reasons

```

And i found the reason was due to attempting to create an agent process within another agent process by accessing the agentNetwork. 

`self.AllSensors[SensorID]=agentNetwork.add_agent(agentType= SensorAgent, log_mode=False)
`
the exceiption was avoided by commenting out the lines 115 and 167 for example.

UPDATE:
Specifically, this is due to attempting to serialise the AgentNetwork object (default behaviour in calling agent functions) which raises the exception since the `agentNetwork` instance contains `self.dashboard_proc` which is a spawned multiprocessing `Process` (and cannot be serialised) for the dashboard.

we can find the snippet is in agents.py for the AgentNetwork class:
```
        if dashboard_modules is not False:
            self.dashboard_proc = Process(target=AgentDashboard, args=(dashboard_modules,dashboard_update_interval,dashboard_max_monitors, ip_addr,dashboard_port,self))
            self.dashboard_proc.start()
```

I will think of a way to resolve this completely.

**Comment by BeSeeTek** [comment]
Ok.

We need the Met4FOFDatareceiver Agent to spwan sensor nodes.

If we have an external sensor array calss witch could swan agents this should work fine.
By the cration of the data Receiver node we pass an pointer to this to an instance of the sensor array class.

**Comment by bangxiangyong** [comment]
Great, thanks ! I have come to understand that intention as well from the code.

**Comment by bangxiangyong** [comment]
referring to latest commit 3224c036ec0a209d38bc7ff9da85168c39592a22

Managed to get the code working and appears to me that the Sensor Agents are successfully sending out the sensor data:
```
(SensorAgent_1): Sending: {'ProtMsg': id: 1689452544
sample_number: 3981519
unix_time: 1596797888
unix_time_nsecs: 622002166
time_uncertainty: 112
Data_01: 1.0535024404525757
Data_02: 0.890688419342041
Data_03: 10.151932716369629
Data_04: 0.003195841796696186
Data_05: -0.008522245101630688
Data_06: -0.003195841796696186
Data_07: 4.524524688720703
Data_08: -12.20421028137207
Data_09: -101.7470474243164
Data_10: 34.005062103271484
Data_11: -7.47675895690918
Data_12: -8.014213562011719
Data_13: -7.432747840881348
, 'Type': 'Data'}
```

**Comment by BjoernLudwig** [comment]
Sounds great! Does that mean, this is resolved? And do we already have some tutorial or other documentation on the coalition feature?

**Comment by BeSeeTek** [comment]
sadly i still cant run the code on my machine see: https://gist.github.com/BeSeeTek/9b9ec5f4869aa9167a94564a15f650d3#comments
